config/routes.rb
Rails.application.routes.draw do
 
  get 'search/search'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  
  get '/search' => 'search#search'
    
  resources :relationships, only: %I[create destroy]
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.comments.new(comment_params)
    @comment.book_id = @book.id
    @comment.save
    
    @comments = @book.comments.order(created_at: :desc)
    
  end
  
  def destroy
    Comment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    @comments = @book.comments.order(created_at: :desc)
    
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model:[@book, @comment], remote: true) do |f| %>
  <%= f.text_area :comment, {rows:'5',placeholder: "コメントをここに", class: "w-100"} %>
  <%= f.submit "送信" %>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comments| %>
  <div class="comments d-flex align-items-center">
    <div class="user-profile">
    <%= link_to user_path(comments.user) do %>
      <%= attachment_image_tag comments.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %><br>
      <%= comments.user.name %>
    <% end %>
    </div>
    <div class="comment">
    <%= comments.comment %>
    </div>
    <div class="destroy-byn">
    <% if comments.user == current_user %>
      <%= link_to "Destroy", book_comment_path(comments.book, comments), method: :delete, remote: true, class:"btn btn-sm btn-danger", data: { confirm: '本当に消しますか?' } %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comments_area").html("<%= j(render 'comments/index', comments: @comments ) %>")
$("textarea").val('')

app/views/comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'comments/index', comments: @comments ) %>")