config/routes.rb
Rails.application.routes.draw do
 
  get 'search/search'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  
  get '/search' => 'search#search'
    
  resources :relationships, only: %I[create destroy]
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  
  def follow(user_id)
   follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
   follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
   following_user.include?(user)
  end
  
  
  attachment :profile_image
  
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.page(params[:page]).reverse_order
    
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page]).reverse_order
    @day_quotient = @books.created_today.count / @books.created_yesterday.count rescue 0
    @count_2_week = @books.created_2_week_sum.count - @books.created_1_week.count
    @count_1_week = @books.created_1_week.count
    @week_quotient = @count_1_week / @count_2_week rescue 0
    @search_params = book_search_params
    if @search_params[:date] != nil
      @search_books = @books.search(@search_params)
    end
    
  end
  
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following_user
    render 'show_follow'
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user
    render 'show_follower'
  end
 

  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def book_search_params
    params.fetch(:search, {}).permit(:date)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%=link_to user.follower.count, following_user_path(user) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%=link_to user.followed.count, followers_user_path(user) %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <% if user != current_user %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-info" %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-success" %>
      <% end %>
    <% else %>
    <%= link_to "", edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, autofocus: true %>
  </div>
  <div class="form-group">
    <label for="book_opiniton">Opinion</label>
    <%= f.text_area :body, autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book' %>
  </div>
  <% end %>
</div>

app/views/users/_search.html.erb
<% if @search_params[:date] == nil %>
  0
<% else %>
  <%= @search_books.count %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %>
                 prohibited this obj from being saved: 
          </h2>
          <ul>
       	  <% @user.errors.full_messages.each do |message| %>
      	  <li><%= message %></li>
      	  <% end %>
          </ul>
        </div>
      <% end %>
      
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, autofocus: true, class:"form-control name" %>
        </div>
        <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, class:"form-control-file user_image" %>
        </div>
        <div class="form-group">
        <label for="user_introduvtion">Introduction</label>
        <%= f.text_area :introduction, class:"form-control introduction" %>
        </div>
        <div class="form-group">
        <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
  <%= render 'users/list', user: @user, book: @book %> 
  
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% User.all.where.not(id: current_user.id).each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= "フォロー数: #{user.follower.count}" %></td>
            <td><%= "フォロワー数: #{user.followed.count}" %></td>
            <td>
              <% unless user == current_user %>
                <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
          <%= paginate @users %>
        </tbody>
      </table>
    </div>
  
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %> 
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
              <% end %>
              </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>コメント数：<%= book.comments.count %></td>
          </tr>
          <% end %>
          <%= paginate @books %>
        </tbody>
      </table>
      <h2>投稿数の前日比・前週比</h2>
      <table border="1" width="600" height="100" cellpadding="10">
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
        <tr>
          <td><%= @books.created_today.count %></td>
          <td><%= @books.created_yesterday.count %></td>
          <td><%= number_to_percentage(@day_quotient) %></td>
        </tr>
      </table>
      <table border="1" width="600" height="100" cellpadding="10" class="my-2">
        <tr>
          <th>今週の投稿数</th>
          <th>前週の投稿数</th>
          <th>前週比</th>
        </tr>
        <tr>
          <td><%= @count_1_week %></td>
          <td><%= @count_2_week %></td>
          <td><%= number_to_percentage(@week_quotient) %></td>
        </tr>
      </table>
      <h2>7日間分の投稿数</h2>
      <table border="1" width="600" height="100" cellpadding="10">
        <tr>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </tr>
        <tr>
          <td><%= @books.created_6_day_ago.count %></td>
          <td><%= @books.created_5_day_ago.count %></td>
          <td><%= @books.created_4_day_ago.count %></td>
          <td><%= @books.created_3_day_ago.count %></td>
          <td><%= @books.created_2_day_ago.count %></td>
          <td><%= @books.created_yesterday.count %></td>
          <td><%= @books.created_today.count %></td>
        </tr>
      </table>
      <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js' %>
      <canvas id="myChart" width="300" height="200"></canvas>
      
      <%= form_with(scope: :search, url: user_path(@user), method: :get, remote: true) do |f| %>
        <%= f.date_field :date, value: @search_params[:date] %>
        <%= f.submit :"検索" %>
      <% end %>
      <h2>検索結果</h2>
      <table border="1" width="600" height="100" cellpadding="10">
        <tr>
          <th>投稿数</th>
        </tr>
        <tr>
          <td id="search_books_count">
            <%= render "users/search", search_books: @search_books %>
            </td>
        </tr>
      </table>
    </div>
    
  </div>
</div>

<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ["6日前", "5日前", "4日前", "3日前", "2日前", "1日前", "今日"],
        datasets: [{
            label: '投稿した本の数',
            data: [
              "<%= @books.created_6_day_ago.count %>",
              "<%= @books.created_5_day_ago.count %>",
              "<%= @books.created_4_day_ago.count %>",
              "<%= @books.created_3_day_ago.count %>",
              "<%= @books.created_2_day_ago.count %>",
              "<%= @books.created_yesterday.count %>",
              "<%= @books.created_today.count %>"
              ],
            backgroundColor: 'rgba(0, 0, 0, 0)',
            borderWidth: 3,
            borderColor: 'rgba(0, 0, 255, 255)'
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

app/views/users/show.js.erb
$("#search_books_count").html("<%= j(render "users/search", search_books: @search_books) %>");

app/views/users/show_follow.html.erb
<h2>Follow Users</h2>
<% if @user.following_user.empty? %>
<p>ユーザーはいません</p>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.following_user.each do |user| %>
    <tr>
      
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
      <td>  <%= user.name %> </td>
      <td><%= "フォロー数: #{user.follower.count}" %></td>
      <td><%= "フォロワー数: #{user.followed.count}" %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/show_follower.html.erb
<h2>Follower Users</h2>
<% if @user.follower_user.empty? %>
<p>ユーザーはいません</p>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.follower_user.each do |user| %>
    <tr>
      
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
      <td>  <%= user.name %> </td>
      <td><%= "フォロー数: #{user.follower.count}" %></td>
      <td><%= "フォロワー数: #{user.followed.count}" %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>