config/routes.rb
Rails.application.routes.draw do
 
  get 'search/search'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  
  get '/search' => 'search#search'
    
  resources :relationships, only: %I[create destroy]
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  scope :created_today, -> { where(created_at: Time.now.in_time_zone("Tokyo").all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.in_time_zone("Tokyo").all_day) }
  scope :created_2_day_ago, -> { where(created_at: 2.days.ago.in_time_zone("Tokyo").all_day) }
  scope :created_3_day_ago, -> { where(created_at: 3.days.ago.in_time_zone("Tokyo").all_day) }
  scope :created_4_day_ago, -> { where(created_at: 4.days.ago.in_time_zone("Tokyo").all_day) }
  scope :created_5_day_ago, -> { where(created_at: 5.days.ago.in_time_zone("Tokyo").all_day) }
  scope :created_6_day_ago, -> { where(created_at: 6.days.ago.in_time_zone("Tokyo").all_day) }
  scope :created_1_week, -> { where("created_at >= ?", 6.days.ago.in_time_zone("Tokyo").beginning_of_day) }
  scope :created_2_week_sum, -> { where("created_at >= ?", 13.days.ago.in_time_zone("Tokyo").beginning_of_day) }
  
  scope :search, -> (search_params) do
    return if search_params.blank?
    created_day_search(search_params[:date])
  end
  
  scope :created_day_search, -> (date) { where(created_at: date.in_time_zone("Tokyo").all_day) if date.present? }
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book_new = Book.new
    @user = current_user
    @book = Book.page(params[:page]).reverse_order
  end
  
  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book_new.id)
    else
      @user = current_user
      @book = Book.page(params[:page]).reverse_order
      render :index
    end
  end
  
  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = Comment.new
    @comments = @book.comments.order(created_at: :desc)
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book),  method: :delete, remote: true, class: "text-danger" do %>
      ♥<%= book.favorites.count %>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3><%= pluralize(@book.errors.count, "error") %>
                 prohibited this obj from being saved: 
          </h3>
          <ul>
       	  <% @book.errors.full_messages.each do |message| %>
      	  <li><%= message %></li>
      	  <% end %>
          </ul>
        </div>
      <% end %>
      
      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, autofocus: true, class:"form-control book_title" %>
        </div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control-file book_body" %>
        </div>
        <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
     <% if @book_new.errors.any? %>
      <div id="error_explanation">
       <h2><%= pluralize(@book_new.errors.count, "error") %>
               prohibited this obj from being saved: 
       </h2>
       <ul>
     	<% @book_new.errors.full_messages.each do |message| %>
    	 <li><%= message %></li>
    	<% end %>
       </ul>
      </div>
     <% end %>
    
    <%= render 'users/list', user: @user, book: @book_new %> 
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @book.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td id="book_<%= book.id %>">
                <%= render 'books/favorite', book: book %>
              </td>
              <td>コメント数：<%= book.comments.count %></td>
            </tr>
          <% end %>
          <%= paginate @book %>
        </tbody>
      </table>
    </div>
    
  </div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render 'users/list', user: @user, book: @book_new %>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td>
            <%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id="book_<%= @book.id %>">
            <%= render 'books/favorite', book: @book %>
          </td>
          <td>コメント数：<%= @book.comments.count %></td>
          <td>
            <% if @book.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>
            <% end %>
          </td>
          <td>
            <% if @book.user == current_user %>
            <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger", data: { confirm: '本当に消しますか?' } %>
            <% end %>
          </td>
        </tr>
      </table>
      <div id="comments_area">
        <%= render 'comments/index', comments: @comments %>
      </div>
      <div class="new-comment">
        <%= render 'comments/form', comment: @comment, book: @book %>
      </div>
    </div>
  </div>
</div>